### ISSUE TITLE
Reddit highlight new comments stopped working

### ISSUE THREAD

**Issue by jtwill** [Farow/userscripts#4]
I've been using your excellent Reddit highlight new comments (v2.0.0) script for months, but in the last couple days it stopped working. It just does nothing now.

I hope it is something that reddit changed and is easy to fix.

In case you are not able to replicate the issue with your system, I am running Firefox 49.0.2 and GreaseMonkey 3.9. I am also running the extension Reddit Enhancement Suite 5.0.3. Let me know if there is anything you want me to try, or more information needed.

**Comment by Farow** [comment]
It's still working fine for me, can you test with a new profile and only GreaseMonkey installed?

**Comment by jtwill** [comment]
I disabled all extensions except GreaseMonkey, and disabled all user scripts except Reddit Hilight New Comments, and the problem persists. It is as if the script is not even installed -- it does nothing.

**Comment by Farow** [comment]
Does the time selection with the config button appear at all?

**Comment by jtwill** [comment]
No, not even the time selection with config button. Nothing.

**Comment by 097115** [comment]
@Farow, does it work for you nowadays?

It strangely works for me with an old installation of Firefox but as soon as I install it with the new browser, it stops (the time selecting button on reddit thread pages appears but even selecting time manually fails to highlight these fresh comments).

**Comment by Farow** [comment]
@097115 I just tested it on v61.0.2 and it works fine on old reddit. I'd suggest using violentmonkey instead of greasemonkey since the latter broke almost all scripts with an update.

**Comment by NoXPhasma** [comment]
This addon stops working on threads with reddit media ([example](https://old.reddit.com/r/linux_gaming/comments/appaqs/im_looking_for_linux_users_to_help_me_test_my/)). As there are now two more nested divs. I was able to fix this with this patch:

```patch
--- a.js	2019-02-12 10:29:07.083480612 +0100
+++ b.js	2019-02-12 10:31:07.934249968 +0100
@@ -35,7 +35,7 @@
 			return;
 		}
 
-		let thread = document.getElementById('siteTable').firstChild.className.match(/id-(t3_[^ ]+)/)[1],
+		let thread = $('#siteTable').closest('div').next().find(/id-(t3_[^ ]+)/),
 			now    = Date.now()
 		;
 
```

**Comment by Farow** [comment]
I pushed a fix for threads with media content, which was reported by someone who deleted their comment. If anyone is still facing an issue feel free to reopen it.

f11e2ad90c0507bfcc99222119ef548ad384d0da
